spring.application.name=cineBoot

spring.datasource.url=jdbc:mysql://localhost:3306/cinebootdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sWsn@$2Q
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver